// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBbQDjEOf1PQZV5dtYguKe0JlqXyitN6k',
    appId: '1:372780503009:web:6b7fb5c2b047445cfdcca0',
    messagingSenderId: '372780503009',
    projectId: 'hrms-e213a',
    authDomain: 'hrms-e213a.firebaseapp.com',
    storageBucket: 'hrms-e213a.firebasestorage.app',
    measurementId: 'G-7X78VWL616',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkt-UFYtX7X0EAqagtvK74qFDpYp72rq4',
    appId: '1:372780503009:android:02c9eae212f9c851fdcca0',
    messagingSenderId: '372780503009',
    projectId: 'hrms-e213a',
    storageBucket: 'hrms-e213a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLvXRLGpI2Ez1MoDPH4jsbtgDOokaUL7Y',
    appId: '1:372780503009:ios:2608b03ae4bd98c3fdcca0',
    messagingSenderId: '372780503009',
    projectId: 'hrms-e213a',
    storageBucket: 'hrms-e213a.firebasestorage.app',
    iosBundleId: 'com.example.hrms',
  );
}
